apiVersion: v1
kind: Service
metadata:
  name: mysql-node
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30006  #  Choose a port between 30000-32767
  selector:
    app: mysql
