apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
stringData:
  mysql-root-password: "{{ .Values.mysqlRootPassword }}"
  mysql-user-password: "{{ .Values.mysqlPassword }}"
