// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/transaction.proto

package proto

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Transaction service

func NewTransactionEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Transaction service

type TransactionService interface {
	GetBalanceSummary(ctx context.Context, in *BalanceSummaryRequest, opts ...client.CallOption) (*BalanceSummaryResponse, error)
}

type transactionService struct {
	c    client.Client
	name string
}

func NewTransactionService(name string, c client.Client) TransactionService {
	return &transactionService{
		c:    c,
		name: name,
	}
}

func (c *transactionService) GetBalanceSummary(ctx context.Context, in *BalanceSummaryRequest, opts ...client.CallOption) (*BalanceSummaryResponse, error) {
	req := c.c.NewRequest(c.name, "Transaction.GetBalanceSummary", in)
	out := new(BalanceSummaryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Transaction service

type TransactionHandler interface {
	GetBalanceSummary(context.Context, *BalanceSummaryRequest, *BalanceSummaryResponse) error
}

func RegisterTransactionHandler(s server.Server, hdlr TransactionHandler, opts ...server.HandlerOption) error {
	type transaction interface {
		GetBalanceSummary(ctx context.Context, in *BalanceSummaryRequest, out *BalanceSummaryResponse) error
	}
	type Transaction struct {
		transaction
	}
	h := &transactionHandler{hdlr}
	return s.Handle(s.NewHandler(&Transaction{h}, opts...))
}

type transactionHandler struct {
	TransactionHandler
}

func (h *transactionHandler) GetBalanceSummary(ctx context.Context, in *BalanceSummaryRequest, out *BalanceSummaryResponse) error {
	return h.TransactionHandler.GetBalanceSummary(ctx, in, out)
}
