apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: asset-price-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: asset-price-service
  template:
    metadata:
      labels:
        app: asset-price-service
    spec:
      containers:
        - name: asset-price-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.environment }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          envFrom:
            {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ .Values.secrets.name }}
            {{- end }}
            {{- if .Values.configmap.enabled }}
            - configMapRef:
                name: {{ .Values.configmap.name }}
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/config.toml  # Mount it as a file
              subPath: config.toml
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.configmap.name }}
